/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpCircleCheck: typeof import('~icons/ep/circle-check')['default']
    IEpFinished: typeof import('~icons/ep/finished')['default']
    IEpFolder: typeof import('~icons/ep/folder')['default']
    IEpGrid: typeof import('~icons/ep/grid')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpOdometer: typeof import('~icons/ep/odometer')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    IEpSort: typeof import('~icons/ep/sort')['default']
    IEpSortDown: typeof import('~icons/ep/sort-down')['default']
    IEpSortUp: typeof import('~icons/ep/sort-up')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTickets: typeof import('~icons/ep/tickets')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
